version: "3.1"

services:
  db:
    image: postgres
    container_name: meschat_db
    environment:
      POSTGRES_DB: Meschat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    env_file:
      - .env
  backend:
    image: meschat_backend
    container_name: meschat_django
    depends_on:
      - db
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    image: react
    container_name: meschat_react
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
  socket:
    image: socket
    container_name: meschat_socket
    command: node index.js --host=0.0.0.0
    ports:
      - "8081:8081"
